# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

# Text to speech
tts:
  - platform: google_translate

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

# Flux
switch:
  - platform: flux
    lights:
      - light.bedroom_light
      - light.boys_bedroom_light
      - light.ben_s_bedroom_light
    name: "Adaptive Lighting Upstairs"
    start_colortemp: 4500
    stop_colortemp: 2700
    disable_brightness_adjust: true
    mode: mired
  - platform: flux
    lights:
      - light.living_room_light
      - light.living_room_tv_backlight
    name: "Adaptive Lighting Living Room"
    start_colortemp: 4500
    stop_colortemp: 3000
    disable_brightness_adjust: true
    mode: mired
  - platform: flux
    lights:
      - light.cooker_hood_light
      - light.kitchen_light
      - light.kitchen_lightstrip
      - light.utility_room_light
    name: "Adaptive Lighting Kitchen"
    start_colortemp: 4500
    stop_colortemp: 3500
    sunset_colortemp: 3500
    disable_brightness_adjust: true
    mode: mired
  - platform: flux
    lights:
      - light.heathers_bedside_lamp
      - light.neils_desk_filament_lamp
      - light.neils_bedside_lamp
    name: "Adaptive Lighting Bedroom Lamps"
    brightness: 1
