substitutions:
  name: apollo-msr-1-38c3bc
  friendly_name: Bedroom Presence Sensor

packages:
  ApolloAutomation.MSR-1: github://ApolloAutomation/MSR-1/Integrations/ESPHome/MSR-1.yaml

esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}

esp32:
  framework:
    type: esp-idf

api:
  encryption:
    key: !secret apollo-msr-1-38c3bc_api_encryption_key

ota:
  platform: esphome
  password: !secret apollo-msr-1-38c3bc_ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  power_save_mode: light
  fast_connect: True

web_server: !remove

logger:

bluetooth_proxy:
  active: true

esp32_ble_tracker:
  scan_parameters:
    active: true

light:
    platform: esp32_rmt_led_strip
    id: rgb_light
    name: RGB Light
    pin: GPIO3
    num_leds: 1
    rmt_channel: 0
    rgb_order: GRB
    chipset: ws2812
