substitutions:
  name: esp32-devkit
  friendly_name: ESP32 DEVKIT

packages:
  esphome.bluetooth-proxy: github://esphome/bluetooth-proxies/esp32-generic/esp32-generic.yaml@main

esphome:
  name: ${name}
  name_add_mac_suffix: False
  friendly_name: ${friendly_name}

esp32:
  board: esp32doit-devkit-v1

api:
  encryption:
    key: "Uq40/nmVdDMFbkdKni26G094QmrZaYJL7KB8fQrTd40="

improv_serial:

esp32_improv:
  authorizer: none

network:
  enable_ipv6: True

wifi:
  ap:
  enable_btm: True
  enable_rrm: True

captive_portal:

ota:
  - platform: esphome
    password: "e49b75620bcc6b99db88f016841a8d95"

button:
  - platform: restart
    name: Restart

sensor:
  - platform: wifi_signal
    disabled_by_default: True
    name: "WiFi Signal"
  - platform: internal_temperature
    disabled_by_default: True
    name: "ESP Temperature"

status_led:
  pin:
    number: LED
    ignore_strapping_warning: True
