substitutions:
  name: esp32-bluetooth-proxy-748090
  friendly_name: Landing Bluetooth Proxy

packages:
  esphome.bluetooth-proxy: github://esphome/bluetooth-proxies/esp32-generic/esp32-generic.yaml@main

esphome:
  name: ${name}
  name_add_mac_suffix: False
  friendly_name: ${friendly_name}

api:
  encryption:
    key: !secret esp32-bluetooth-proxy-748090_api_encryption_key

esp32:
  board: esp32doit-devkit-v1

network:
  enable_ipv6: True

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  enable_btm: True
  enable_rrm: True
  ap:

captive_portal:

ota:
  - platform: esphome
    password: !secret esp32-bluetooth-proxy-748090_ota_password

improv_serial:

esp32_improv:
  authorizer: none

button:
  - platform: restart
    name: Restart

sensor:
  - platform: wifi_signal
    name: "WiFi Signal"

status_led:
  pin:
    number: LED
    ignore_strapping_warning: True
