substitutions:
  name: esp32-bluetooth-proxy-ab7f3c
  friendly_name: Bluetooth Proxy ab7f3c

packages:
  esphome.bluetooth-proxy: github://esphome/firmware/bluetooth-proxy/esp32-generic.yaml@main

esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}

api:
  encryption:
    key: !secret esp32-bluetooth-proxy-ab7f3c_api_encryption_key

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: True

ota:
  password: !secret esp32-bluetooth-proxy-ab7f3c_ota_password

status_led:
  pin:
    number: GPIO2
    ignore_strapping_warning: True

i2c:

sensor:
  - platform: wifi_signal
    name: WiFi Status
  - platform: bh1750
    name: Illuminance
    update_interval: 5s

button:
  - platform: restart
    name: Restart