esphome:
  name: esphome-web-748090
  friendly_name: iBeacon 00895a183a8

esp32:
  board: esp32dev
  framework:
    type: esp-idf

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret esphome-web-748090_api_encryption_key

ota:
  password: !secret esphome-web-748090_ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: True

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: Esphome-Web-748090

captive_portal:

esp32_ble_beacon:
  type: iBeacon
  uuid: 35a011e9-67a6-e449-b07f-300895a183a8

status_led:
  pin:
    number: GPIO2
    ignore_strapping_warning: True

sensor:
  - platform: esp32_hall
    name: ESP32 Hall Sensor
  - platform: internal_temperature
    name: Internal Temperature
  - platform: wifi_signal
    name: WiFi Signal Sensor

button:
  - platform: restart
    name: Restart