substitutions:
  name: everything-presence-lite-2fbc58
  friendly_name: Landing Presence Sensor
packages:
  EverythingSmartTechnology.Everything_Presence_Lite: github://everythingsmarthome/everything-presence-lite/everything-presence-lite-ha.yaml@main

esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}

api:
  encryption:
    key: !secret everything-presence-lite-2fbc58_api_encryption_key


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

ota:
  - platform: esphome
    password: !secret everything-presence-lite-2fbc58_ota_password

sensor:
  - platform: dht
    pin: 32
    temperature:
      name: "Temperature"
    humidity:
      name: "Humidity"
      accuracy_decimals: 1
  - platform: wifi_signal
    disabled_by_default: True
    name: "WiFi Signal"
  - platform: internal_temperature
    disabled_by_default: True
    name: "ESP Temperature"
