substitutions:
  name: everything-presence-lite-5ba230
  friendly_name: Bedroom Presence Sensor

packages:
  EverythingSmartTechnology.Everything_Presence_Lite: github://everythingsmarthome/everything-presence-lite/everything-presence-lite-ha-co2.yaml@main

esphome:
  name: ${name}
  name_add_mac_suffix: False
  friendly_name: ${friendly_name}

api:
  encryption:
    key: !secret everything-presence-lite-5ba230_api_encryption_key

network:
  enable_ipv6: True

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  enable_btm: True
  enable_rrm: True

ota:
  - platform: esphome
    password: !secret everything-presence-lite-5ba230_ota_password

sensor:
  - platform: wifi_signal
    disabled_by_default: True
    name: "WiFi Signal"
  - platform: internal_temperature
    disabled_by_default: True
    name: "ESP Temperature"
