substitutions:
  name: everything-presence-lite-8fae78
  friendly_name: Ben's Bedroom Presence Sensor

packages:
  EverythingSmartTechnology.Everything_Presence_Lite: github://everythingsmarthome/everything-presence-lite/everything-presence-lite-ha.yaml@main

esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}

api:
  encryption:
    key: !secret everything-presence-lite-8fae78_api_encryption_key

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

ota:
  - platform: esphome
    password: !secret everything-presence-lite-8fae78_ota_password

sensor:
  - platform: wifi_signal
    disabled_by_default: True
    name: "WiFi Signal"
  - platform: internal_temperature
    disabled_by_default: True
    name: "ESP Temperature"
