substitutions:
  name: everything-presence-lite-214fd8
  friendly_name: Kitchen Presence Sensor

packages:
  EverythingSmartTechnology.Everything_Presence_Lite: github://everythingsmarthome/everything-presence-lite/everything-presence-lite-ha-no-ble.yaml@main

esphome:
  name: ${name}
  name_add_mac_suffix: False
  friendly_name: ${friendly_name}

api:
  encryption:
    key: !secret everything-presence-lite-214fd8_api_encryption_key

logger:
  baud_rate: 0

improv_serial: !remove

network:
  enable_ipv6: True

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  enable_btm: True
  enable_rrm: True
  ap:

captive_portal:

ota:
  - platform: esphome
    password: !secret everything-presence-lite-214fd8_ota_password

esp32_improv:
  authorizer: none

sensor:
  - platform: dht
    pin: 32
    temperature:
      name: "Temperature"
    humidity:
      name: "Humidity"
      accuracy_decimals: 1
  - platform: wifi_signal
    name: "WiFi Signal"
