substitutions:
  name: everything-presence-lite-ccb890
  friendly_name: Living Room Presence Sensor

packages:
  EverythingSmartTechnology.Everything_Presence_Lite: github://everythingsmarthome/everything-presence-lite/everything-presence-lite-ha-no-ble.yaml@main

esphome:
  name: ${name}
  name_add_mac_suffix: False
  friendly_name: ${friendly_name}

api:
  encryption:
    key: !secret everything-presence-lite-ccb890_api_encryption_key

logger:
  baud_rate: 0

improv_serial: !remove

network:
  enable_ipv6: True

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  enable_btm: True
  enable_rrm: True
  ap:

captive_portal:

ota:
  - platform: esphome
    password: !secret everything-presence-lite-ccb890_ota_password

esp32_improv:
  authorizer: none

sensor:
  - platform: wifi_signal
    name: "WiFi Signal"
