substitutions:
  name: localbytes-plug-pm-8ca200
  friendly_name: Tumble Dryer
packages:
  localbytes.plug-pm: github://LocalBytes/esphome-localbytes-plug/localbytes-plug-pm.yaml@main
esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}

api:
  encryption:
    key: !secret localbytes-plug-pm-8ca200_api_encryption_key

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

ota:
  - platform: esphome
    password: !secret localbytes-plug-pm-8ca200_ota_password