substitutions:
  name: localbytes-plug-pm-f108d4
  friendly_name: Dishwasher

packages:
  localbytes.plug-pm: github://LocalBytes/esphome-localbytes-plug/localbytes-plug-pm.yaml@main

esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}

esp8266:
  early_pin_init: false

api:
  encryption:
    key: !secret localbytes-plug-pm-f108d4_api_encryption_key

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: True

ota:
  - platform: esphome
    password: !secret localbytes-plug-pm-f108d4_ota_password