substitutions:
  name: localbytes-plug-pm-8ca11b
  friendly_name: Living Room Fan

packages:
  localbytes.plug-pm: github://neilmartin83/esphome-localbytes-plug/localbytes-plug-pm.yaml@patch-2

esphome:
  name: ${name}
  name_add_mac_suffix: False
  friendly_name: ${friendly_name}

api:
  encryption:
    key: !secret localbytes-plug-pm-8ca11b_api_encryption_key

logger:
  baud_rate: 0

network:
  enable_ipv6: True

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

ota:
  - platform: esphome
    password: !secret localbytes-plug-pm-8ca11b_ota_password
