substitutions:
  name: localbytes-plug-pm-d5e5b5
  friendly_name: Heather's CPAP Machine

packages:
  localbytes.plug-pm: github://neilmartin83/esphome-localbytes-plug/localbytes-plug-pm.yaml@patch-2

esphome:
  name: ${name}
  name_add_mac_suffix: False
  friendly_name: ${friendly_name}

api:
  encryption:
    key: !secret localbytes-plug-pm-d5e5b5_api_encryption_key

logger:
  baud_rate: 0

network:
  enable_ipv6: True

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

ota:
  - platform: esphome
    password: !secret localbytes-plug-pm-d5e5b5_ota_password
